// Source-backed introductory lessons. Original summaries, no operational procedures.
module.exports = [
 {slug:'metar', title:'METAR: как читать основные группы', description:'Короткий урок для пилотов: время наблюдения, ветер, видимость, облачность, температура и QNH в METAR. Учебный пример и самопроверка.', eyebrow:'Метеорология', section:'3.7', study:'meteorology', checks:['3.7:2','3.7:4','3.7:12'],
 body:
 '<section id="basics"><h2>Наблюдение и прогноз — разные вещи</h2><p>METAR описывает наблюдавшуюся погоду на аэродроме в определённое время. SPECI — специальная сводка при существенном изменении условий. Если в конце есть TREND, это краткосрочный прогноз на два часа после наблюдения.</p></section>'+
 '<section id="example"><h2>Разберём учебный пример</h2><p>Это вымышленная сводка для упражнения, не текущая погода.</p><div class="metar-example"><code>METAR VHHH 021200Z 24015G25KT 7000 -RA BKN020 18/16 Q1013 NOSIG</code></div>'+
 '<dl class="decode-list"><div><dt>VHHH · 021200Z</dt><dd>Аэродром Гонконг; 2-е число, 12:00 UTC. Месяц и год эта группа не содержит.</dd></div><div><dt>24015G25KT</dt><dd>Ветер с направления 240°, 15 узлов, порывы до 25 узлов. KT — узлы; MPS означает метры в секунду.</dd></div><div><dt>7000 · -RA</dt><dd>Видимость 7000 м; слабый дождь. RA — дождь, знак «−» — слабая интенсивность.</dd></div><div><dt>BKN020</dt><dd>Облачность 5–7 октантов; основание слоя 2000 футов над аэродромом. Число после BKN — сотни футов, не октанты.</dd></div><div><dt>18/16 · Q1013</dt><dd>Температура +18 °C, точка росы +16 °C; QNH 1013 гПа.</dd></div><div><dt>NOSIG</dt><dd>В ближайшие два часа не ожидается существенных изменений.</dd></div></dl></section>'+
 '<section id="remember"><h2>Что легко перепутать</h2><p>Видимость и RVR не одно и то же: RVR относится к конкретной ВПП и записывается группой, начинающейся с R. Высота облаков в коде — не высота относительно уровня моря. Смотрите единицы: в американских сводках видимость может быть в SM, давление — в группе A, а не Q.</p></section>',
 sources:[{title:'Hong Kong Observatory: Decoding METAR/SPECI',url:'https://www.hko.gov.hk/en/aviat/decode_metar.htm'},{title:'NOAA / NWS: METAR',url:'https://www.weather.gov/asos/METAR.html'},{title:'NOAA / NWS: Decoding METARs',url:'https://www.weather.gov/lzk/metar.htm'}]
 },
 {slug:'course-heading-track', title:'Course, heading и track: в чём разница', description:'Планируемое направление, направление носа и фактический путь над землёй. Короткий разбор навигационных терминов с примером и вопросами из базы ЧЛЭ.', eyebrow:'Воздушная навигация', section:'3.6.2', study:'airbus-a320-navigation', checks:['3.6.2:4','3.6.2:5','3.6.2:6'],
 body:
 '<section id="basics"><h2>Три разных направления</h2><dl class="concept-list"><div><dt>Course · план</dt><dd>Планируемое направление пути над землёй.</dd></div><div><dt>Heading · нос самолёта</dt><dd>Направление, в котором ориентирована продольная ось самолёта.</dd></div><div><dt>Track · фактический путь</dt><dd>Направление движения самолёта над землёй.</dd></div></dl><p>В русской терминологии heading — курс самолёта, course — заданный путевой угол, track — фактический путевой угол. Поэтому переводить все три слова просто как «курс» неудобно.</p></section>'+
 '<section id="example"><h2>Почему они могут различаться</h2><p>Боковой ветер может смещать самолёт относительно запланированного пути. Если поправка на ветер подобрана правильно, track совпадает с course, а heading может отличаться.</p>'+
 '<figure class="navigation-figure"><svg viewBox="0 0 400 180" role="img" aria-labelledby="wind-title wind-desc"><title id="wind-title">Боковой ветер меняет путь над землёй</title><desc id="wind-desc">Нос направлен вдоль запланированного пути, но без поправки ветер смещает фактическую траекторию в сторону.</desc><path class="planned-path" d="M40 50H360"/><path class="actual-path" d="M40 50L360 140"/><path class="wind-path" d="M230 8V40m-6-8 6 8 6-8"/><path class="aircraft-path" d="m65 50-18-9 4 9-4 9Z"/><circle cx="40" cy="50" r="4"/></svg><figcaption><span class="planned-key">Course: запланировано</span><span class="actual-key">Track: фактически</span><span>Стрелка сверху — ветер. Схема условная, без масштаба.</span></figcaption></figure>'+
 '<p>Пример: course 090°, heading 090°, но из-за ветра track 100°. Нос смотрит на восток, а путь над землёй отклонён. Числа условные и не задают поправку на ветер.</p></section>'+
 '<section id="remember"><h2>Сравнивайте одинаковые отсчёты</h2><p>Угол может отсчитываться от истинного или магнитного севера. Сравнивайте значения, приведённые к одной системе отсчёта. Угол между heading и track — угол сноса; поправка на ветер применяется к course для получения нужного heading.</p></section>',
 sources:[{title:'FAA: Pilot’s Handbook of Aeronautical Knowledge, глава 16, стр. 16-10',url:'https://www.faa.gov/sites/faa.gov/files/18_phak_ch16.pdf#page=10'}]
 }
];
